import astro1 from "@/assets/astrologers/astrologer1.png";
import astro2 from "@/assets/astrologers/astrologer2.png";
import astro3 from "@/assets/astrologers/astrologer3.png";

export interface Astrologer {
  id: string;
  name: string;
  category: string;
  specialization: string;
  experience: string;
  consultations: string;
  rating: number;
  languages: string[];
  bio: string;
  image: string;
  online: boolean;
  isPaid: boolean;
  price: number;
  reviews: number;
  color?: string; // Optional for UI gradients
}

export const categories = [
  'All', 'Love', 'Career', 'Wealth', 'Health', 'Vastu', 'Numerology', 'Tarot', 'Palmistry', 'Marriage', 'Finance', 'Education', 'Spiritual'
];

export const astrologers: Astrologer[] = [
  {
    id: "arjun-sharma",
    name: "Pandit Arjun Sharma",
    category: "Love",
    specialization: "Love & Relationships",
    experience: "12+ Years",
    consultations: "18,000+",
    rating: 4.8,
    reviews: 2450,
    languages: ["Hindi", "Gujarati", "English"],
    bio: "Expert in love, breakup healing, and relationship compatibility using Vedic astrology.",
    image: astro1,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-pink-500/20 to-purple-500/20'
  },
  {
    id: "meera-joshi",
    name: "Acharya Meera Joshi",
    category: "Love",
    specialization: "Marriage & Compatibility",
    experience: "10+ Years",
    consultations: "14,500+",
    rating: 4.9,
    reviews: 1890,
    languages: ["Hindi", "English"],
    bio: "Specialist in marriage timing and kundli matching.",
    image: astro3,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-rose-500/20 to-pink-500/20'
  },
  {
    id: "rakesh-trivedi",
    name: "Dr. Rakesh Trivedi",
    category: "Career",
    specialization: "Career & Business",
    experience: "15+ Years",
    consultations: "21,000+",
    rating: 4.7,
    reviews: 3120,
    languages: ["Hindi", "English"],
    bio: "Helps with job growth, career direction, and promotions.",
    image: astro2,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-blue-500/20 to-cyan-500/20'
  },
  {
    id: "sandeep-mishra",
    name: "Guru Sandeep Mishra",
    category: "Finance",
    specialization: "Wealth & Finance",
    experience: "14+ Years",
    consultations: "19,000+",
    rating: 4.8,
    reviews: 2100,
    languages: ["Hindi"],
    bio: "Provides guidance on wealth and financial stability.",
    image: astro2,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-indigo-500/20 to-blue-500/20'
  },
  {
    id: "vivek-shastri",
    name: "Pandit Vivek Shastri",
    category: "Marriage",
    specialization: "Marriage Timing",
    experience: "13+ Years",
    consultations: "17,000+",
    rating: 4.9,
    reviews: 1560,
    languages: ["Hindi", "Gujarati"],
    bio: "Expert in marriage timing and relationship issues.",
    image: astro1,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-amber-500/20 to-orange-500/20'
  },
  {
    id: "kavita-pathak",
    name: "Acharya Kavita Pathak",
    category: "Marriage",
    specialization: "Kundli Matching",
    experience: "11+ Years",
    consultations: "13,000+",
    rating: 4.8,
    reviews: 1240,
    languages: ["Hindi", "English"],
    bio: "Specialist in kundli matching and dosha solutions.",
    image: astro3,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-orange-500/20 to-red-500/20'
  },
  {
    id: "mahesh-bhatt",
    name: "Guru Mahesh Bhatt",
    category: "Wealth",
    specialization: "Financial Astrology",
    experience: "16+ Years",
    consultations: "22,000+",
    rating: 4.7,
    reviews: 4500,
    languages: ["Hindi"],
    bio: "Guides wealth creation and financial planning.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 25,
    color: 'from-yellow-500/20 to-amber-500/20'
  },
  {
    id: "anil-vyas",
    name: "Pandit Anil Vyas",
    category: "Finance",
    specialization: "Business Growth",
    experience: "12+ Years",
    consultations: "15,000+",
    rating: 4.8,
    reviews: 2300,
    languages: ["Gujarati", "Hindi"],
    bio: "Helps business owners grow and scale.",
    image: astro1,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-emerald-500/20 to-teal-500/20'
  },
  {
    id: "neelam-verma",
    name: "Acharya Neelam Verma",
    category: "Health",
    specialization: "Health & Wellness",
    experience: "10+ Years",
    consultations: "12,500+",
    rating: 4.9,
    reviews: 1780,
    languages: ["Hindi", "English"],
    bio: "Focus on health, mental peace, and healing.",
    image: astro3,
    online: true,
    isPaid: false,
    price: 15,
    color: 'from-teal-500/20 to-emerald-500/20'
  },
  {
    id: "aditya-giri",
    name: "Swami Aditya Giri",
    category: "Spiritual",
    specialization: "Spiritual Growth",
    experience: "18+ Years",
    consultations: "25,000+",
    rating: 5.0,
    reviews: 6200,
    languages: ["Hindi"],
    bio: "Guides meditation, karma, and life purpose.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 49,
    color: 'from-violet-500/20 to-purple-500/20'
  },
  {
    id: "rahul-sharma-acharya",
    name: "Acharya Rahul Sharma",
    category: "Love",
    specialization: "Breakup Healing, Relationship",
    experience: "12+ Years",
    consultations: "9,200+",
    rating: 4.8,
    reviews: 3500,
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Renowned expert in resolving complex relationship issues and healing emotional wounds.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 25,
    color: 'from-pink-600/20 to-rose-600/20'
  },
  {
    id: "vikram-joshi-pandit",
    name: "Pandit Vikram Joshi",
    category: "Vastu",
    specialization: "Home & Office Vastu",
    experience: "15+ Years",
    consultations: "12,500+",
    rating: 4.9,
    reviews: 4200,
    languages: ["Hindi", "Sanskrit", "Marathi"],
    bio: "Specialist in traditional Vedic Vastu Shastra for residential and commercial spaces.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 40,
    color: 'from-orange-600/20 to-yellow-600/20'
  },
  {
    id: "neha-kapoor-astro",
    name: "Astro Neha Kapoor",
    category: "Tarot",
    specialization: "Tarot Reading, Angel Guidance",
    experience: "7+ Years",
    consultations: "4,800+",
    rating: 4.7,
    reviews: 1200,
    languages: ["English", "Hindi"],
    bio: "Intuitive Tarot reader providing clarity on love, career, and personal growth.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 30,
    color: 'from-purple-600/20 to-indigo-600/20'
  },
  {
    id: "sandeep-mishra-guru",
    name: "Guruji Sandeep Mishra",
    category: "Palmistry",
    specialization: "Hand Analysis, Life Predictions",
    experience: "14+ Years",
    consultations: "10,000+",
    rating: 4.8,
    reviews: 2800,
    languages: ["Hindi", "Bhojpuri"],
    bio: "Expert palmist with over a decade of experience in decoding life's blueprint from hands.",
    image: astro2,
    online: false,
    isPaid: true,
    price: 35,
    color: 'from-amber-600/20 to-brown-600/20'
  },
  {
    id: "kavita-trivedi-dr",
    name: "Dr. Kavita Trivedi",
    category: "Health",
    specialization: "Medical Astrology, Wellness",
    experience: "10+ Years",
    consultations: "6,500+",
    rating: 4.6,
    reviews: 1500,
    languages: ["Hindi", "English", "Gujarati"],
    bio: "Combining medical knowledge with astrology to provide holistic health and wellness guidance.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 20,
    color: 'from-emerald-600/20 to-teal-600/20'
  },
  {
    id: "sunil-vats-acharya",
    name: "Acharya Sunil Vats",
    category: "Career",
    specialization: "Job Stability, Business Growth",
    experience: "8+ Years",
    consultations: "3,200+",
    rating: 4.7,
    reviews: 900,
    languages: ["Hindi", "Haryanvi"],
    bio: "Assisting professionals and entrepreneurs in navigating their career paths with precision.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 22,
    color: 'from-blue-600/20 to-sky-600/20'
  },
  {
    id: "rajni-vyas-smt",
    name: "Smt. Rajni Vyas",
    category: "Numerology",
    specialization: "Name Correction, Lucky Numbers",
    experience: "6+ Years",
    consultations: "2,500+",
    rating: 4.5,
    reviews: 750,
    languages: ["Hindi", "Gujarati"],
    bio: "Providing numerological solutions for personal and professional success through name and date analysis.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 18,
    color: 'from-lime-600/20 to-green-600/20'
  },
  {
    id: "dinesh-pandey-pandit",
    name: "Pandit Dinesh Pandey",
    category: "Vastu",
    specialization: "Industrial Vastu, Remedies",
    experience: "13+ Years",
    consultations: "8,900+",
    rating: 4.8,
    reviews: 3100,
    languages: ["Hindi", "Awadhi"],
    bio: "Specializing in industrial Vastu and providing effective non-demolition remedies.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 38,
    color: 'from-orange-700/20 to-red-700/20'
  },
  {
    id: "priya-singh-astro",
    name: "Astro Priya Singh",
    category: "Tarot",
    specialization: "Future Forecasting, Relationship",
    experience: "5+ Years",
    consultations: "2,100+",
    rating: 4.6,
    reviews: 600,
    languages: ["English", "Hindi"],
    bio: "A young and intuitive Tarot reader focused on providing practical solutions to life's challenges.",
    image: astro3,
    online: false,
    isPaid: true,
    price: 28,
    color: 'from-fuchsia-600/20 to-pink-600/20'
  },
  {
    id: "rajesh-iyer-guru",
    name: "Guru Rajesh Iyer",
    category: "Wealth",
    specialization: "Stock Market, Investment",
    experience: "11+ Years",
    consultations: "7,400+",
    rating: 4.7,
    reviews: 2100,
    languages: ["Tamil", "English", "Hindi"],
    bio: "Expert in financial astrology with a focus on stock market trends and wealth management.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 32,
    color: 'from-green-700/20 to-emerald-700/20'
  },
  {
    id: "amit-bhardwaj-acharya",
    name: "Acharya Amit Bhardwaj",
    category: "Love",
    specialization: "Inter-caste Marriage, Love Life",
    experience: "9+ Years",
    consultations: "5,600+",
    rating: 4.7,
    reviews: 1800,
    languages: ["Hindi", "Punjabi"],
    bio: "Specialist in love marriage obstacles and providing Vedic remedies for a peaceful family life.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 24,
    color: 'from-rose-600/20 to-pink-700/20'
  },
  {
    id: "suresh-kulkarni-pandit",
    name: "Pandit Suresh Kulkarni",
    category: "Palmistry",
    specialization: "Destiny Decoding, Health Lines",
    experience: "12+ Years",
    consultations: "8,200+",
    rating: 4.8,
    reviews: 2400,
    languages: ["Marathi", "Hindi"],
    bio: "Dedicated palmist helping people understand their destiny through the lines on their palms.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 36,
    color: 'from-cyan-600/20 to-blue-700/20'
  },
  {
    id: "meenakshi-sundaram-dr",
    name: "Dr. Meenakshi Sundaram",
    category: "Health",
    specialization: "Holistic Health, Mental Peace",
    experience: "15+ Years",
    consultations: "15,000+",
    rating: 4.9,
    reviews: 4800,
    languages: ["Tamil", "English", "Hindi"],
    bio: "Expert in combining astrology with traditional wellness practices for physical and mental health.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 40,
    color: 'from-teal-600/20 to-cyan-700/20'
  },
  {
    id: "varun-malhotra-astro",
    name: "Astro Varun Malhotra",
    category: "Numerology",
    specialization: "Business Name, Mobile Numerology",
    experience: "4+ Years",
    consultations: "1,800+",
    rating: 4.5,
    reviews: 450,
    languages: ["Hindi", "English"],
    bio: "Providing modern numerological solutions for business success and personal luck.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 16,
    color: 'from-violet-600/20 to-purple-700/20'
  },
  {
    id: "anjali-deshmukh-smt",
    name: "Smt. Anjali Deshmukh",
    category: "Tarot",
    specialization: "Psychic Reading, Relationship",
    experience: "8+ Years",
    consultations: "4,200+",
    rating: 4.7,
    reviews: 1350,
    languages: ["Marathi", "Hindi", "English"],
    bio: "Intuitive Tarot reader and psychic counselor focusing on emotional well-being and relationships.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 31,
    color: 'from-pink-700/20 to-fuchsia-700/20'
  },
  {
    id: "kamal-kant-acharya",
    name: "Acharya Kamal Kant",
    category: "Vastu",
    specialization: "Vastu for Prosperity, Remedial",
    experience: "10+ Years",
    consultations: "6,800+",
    rating: 4.7,
    reviews: 1900,
    languages: ["Hindi", "Rajasthani"],
    bio: "Expert in Vastu Shastra remedies that bring prosperity and peace to the household.",
    image: astro1,
    online: false,
    isPaid: true,
    price: 29,
    color: 'from-yellow-700/20 to-amber-700/20'
  },
  {
    id: "om-prakash-pandit",
    name: "Pandit Om Prakash",
    category: "Spiritual",
    specialization: "Mantra Jaap, Spiritual Healing",
    experience: "14+ Years",
    consultations: "9,500+",
    rating: 4.9,
    reviews: 3300,
    languages: ["Hindi", "Sanskrit"],
    bio: "Spiritual guide focusing on mantra therapy and ancient Vedic healing techniques.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 34,
    color: 'from-orange-800/20 to-red-800/20'
  },
  {
    id: "shweta-tiwari-astro",
    name: "Astro Shweta Tiwari",
    category: "Love",
    specialization: "Love Compatibility, Marriage",
    experience: "6+ Years",
    consultations: "3,800+",
    rating: 4.6,
    reviews: 1100,
    languages: ["Hindi", "Bhojpuri"],
    bio: "Helping young couples find compatibility and resolve pre-marital anxiety through astrology.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 26,
    color: 'from-rose-700/20 to-pink-800/20'
  },
  {
    id: "vinay-pathak-guru",
    name: "Guru Vinay Pathak",
    category: "Career",
    specialization: "Govt Jobs, Competitive Exams",
    experience: "13+ Years",
    consultations: "8,500+",
    rating: 4.8,
    reviews: 2700,
    languages: ["Hindi", "Bengali"],
    bio: "Specializing in career astrology for students and professionals aiming for government positions.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 33,
    color: 'from-blue-700/20 to-indigo-800/20'
  },
  {
    id: "deepa-nair-acharya",
    name: "Acharya Deepa Nair",
    category: "Numerology",
    specialization: "Signature Analysis, Luck",
    experience: "9+ Years",
    consultations: "5,200+",
    rating: 4.7,
    reviews: 1650,
    languages: ["Malayalam", "English", "Hindi"],
    bio: "Expert numerologist specializing in signature correction and personal luck enhancement.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 27,
    color: 'from-green-600/20 to-emerald-600/20'
  },
  {
    id: "rajesh-pandey-acharya",
    name: "Acharya Rajesh Pandey",
    category: "Vastu",
    specialization: "Vastu for Homes & Plot Selection",
    experience: "12 Years Experience",
    consultations: "7,800+",
    rating: 4.8,
    reviews: 2150,
    languages: ["Hindi", "English", "Sanskrit"],
    bio: "Dedicated Vastu expert specializing in residential harmony and energy balancing for modern homes.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 35,
    color: 'from-amber-600/20 to-orange-700/20'
  },
  {
    id: "alok-shastri-pandit",
    name: "Pandit Alok Shastri",
    category: "Love",
    specialization: "Love Marriage & Family Solutions",
    experience: "8 Years Experience",
    consultations: "4,200+",
    rating: 4.7,
    reviews: 1240,
    languages: ["Hindi", "Sanskrit", "Maithili"],
    bio: "Vedic scholar helping couples overcome obstacles in love marriages and family disputes.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 22,
    color: 'from-pink-600/20 to-rose-700/20'
  },
  {
    id: "shalini-singh-astro",
    name: "Astro Shalini Singh",
    category: "Tarot",
    specialization: "Intuitive Tarot & Crystal Healing",
    experience: "5 Years Experience",
    consultations: "2,900+",
    rating: 4.6,
    reviews: 850,
    languages: ["English", "Hindi"],
    bio: "Empowering individuals through Tarot guidance and crystal energy for personal growth.",
    image: astro3,
    online: false,
    isPaid: true,
    price: 30,
    color: 'from-purple-600/20 to-indigo-700/20'
  },
  {
    id: "pradeep-verma-dr",
    name: "Dr. Pradeep Verma",
    category: "Health",
    specialization: "Medical Astrology & Longevity",
    experience: "14 Years Experience",
    consultations: "9,100+",
    rating: 4.9,
    reviews: 3200,
    languages: ["Hindi", "Punjabi", "English"],
    bio: "Blending ancient medical astrology with modern health awareness for holistic well-being.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 40,
    color: 'from-emerald-600/20 to-teal-700/20'
  },
  {
    id: "mohan-lal-guru",
    name: "Guruji Mohan Lal",
    category: "Palmistry",
    specialization: "Hand Analysis & Fortune Telling",
    experience: "15 Years Experience",
    consultations: "12,000+",
    rating: 4.9,
    reviews: 4800,
    languages: ["Hindi", "Bhojpuri", "Awadhi"],
    bio: "Master palmist with deep knowledge of line interpretations and life event predictions.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 38,
    color: 'from-brown-600/20 to-orange-800/20'
  },
  {
    id: "sneha-reddy-acharya",
    name: "Acharya Sneha Reddy",
    category: "Numerology",
    specialization: "Business Names & Career Luck",
    experience: "7 Years Experience",
    consultations: "3,500+",
    rating: 4.6,
    reviews: 980,
    languages: ["Telugu", "English", "Hindi"],
    bio: "Helping entrepreneurs select lucky names and dates for successful business ventures.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 25,
    color: 'from-blue-600/20 to-cyan-700/20'
  },
  {
    id: "sanjay-kothari-pandit",
    name: "Pandit Sanjay Kothari",
    category: "Career",
    specialization: "Job Stability & Professional Growth",
    experience: "11 Years Experience",
    consultations: "6,700+",
    rating: 4.7,
    reviews: 1850,
    languages: ["Gujarati", "Hindi", "English"],
    bio: "Expert in career path analysis, job changes, and professional relationship management.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 28,
    color: 'from-indigo-600/20 to-blue-800/20'
  },
  {
    id: "deepali-sen-astro",
    name: "Astro Deepali Sen",
    category: "Tarot",
    specialization: "Love, Career & Past Life Insights",
    experience: "6 Years Experience",
    consultations: "3,100+",
    rating: 4.5,
    reviews: 720,
    languages: ["Bengali", "English", "Hindi"],
    bio: "Compassionate Tarot reader providing clarity on relationships and spiritual path.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 24,
    color: 'from-fuchsia-600/20 to-pink-700/20'
  },
  {
    id: "harish-chandra-guru",
    name: "Guruji Harish Chandra",
    category: "Wealth",
    specialization: "Investment & Financial Prosperity",
    experience: "13 Years Experience",
    consultations: "8,400+",
    rating: 4.8,
    reviews: 2900,
    languages: ["Hindi", "Sanskrit", "Marathi"],
    bio: "Guiding individuals towards financial abundance through Vedic wealth remedies.",
    image: astro2,
    online: false,
    isPaid: true,
    price: 36,
    color: 'from-yellow-600/20 to-amber-800/20'
  },
  {
    id: "nandini-rao-acharya",
    name: "Acharya Nandini Rao",
    category: "Vastu",
    specialization: "Commercial Vastu & Interior Design",
    experience: "9 Years Experience",
    consultations: "5,300+",
    rating: 4.7,
    reviews: 1450,
    languages: ["Kannada", "English", "Hindi"],
    bio: "Integrating Vastu principles with modern interior design for prosperous workspaces.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 32,
    color: 'from-teal-600/20 to-green-700/20'
  },
  {
    id: "krishna-murthy-pandit",
    name: "Pandit Krishna Murthy",
    category: "Palmistry",
    specialization: "Hand Lines & Health Warnings",
    experience: "10 Years Experience",
    consultations: "6,200+",
    rating: 4.8,
    reviews: 1950,
    languages: ["Tamil", "English", "Hindi"],
    bio: "Traditional palmist focusing on health indications and major life transitions.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 29,
    color: 'from-sky-600/20 to-blue-700/20'
  },
  {
    id: "smita-gupte-dr",
    name: "Dr. Smita Gupte",
    category: "Health",
    specialization: "Mental Peace & Stress Management",
    experience: "12 Years Experience",
    consultations: "7,500+",
    rating: 4.9,
    reviews: 2400,
    languages: ["Marathi", "English", "Hindi"],
    bio: "Combining psychological insights with astrology for emotional and mental balance.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 34,
    color: 'from-violet-600/20 to-purple-800/20'
  },
  {
    id: "rahul-khanna-astro",
    name: "Astro Rahul Khanna",
    category: "Love",
    specialization: "Breakup Recovery & Relationship Healing",
    experience: "4 Years Experience",
    consultations: "2,200+",
    rating: 4.5,
    reviews: 580,
    languages: ["Hindi", "Punjabi", "English"],
    bio: "Helping young hearts heal from breakups and find true love again.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 18,
    color: 'from-rose-500/20 to-pink-600/20'
  },
  {
    id: "om-prakash-guru-2",
    name: "Guruji Om Prakash",
    category: "Wealth",
    specialization: "Debt Relief & Asset Protection",
    experience: "15 Years Experience",
    consultations: "11,500+",
    rating: 4.9,
    reviews: 4100,
    languages: ["Hindi", "Haryanvi"],
    bio: "Renowned expert in providing remedies for financial crises and safeguarding property.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 39,
    color: 'from-orange-600/20 to-red-700/20'
  },
  {
    id: "preeti-jha-acharya",
    name: "Acharya Preeti Jha",
    category: "Numerology",
    specialization: "Name Correction & Lucky Number Selection",
    experience: "8 Years Experience",
    consultations: "4,800+",
    rating: 4.7,
    reviews: 1300,
    languages: ["Hindi", "Maithili", "English"],
    bio: "Precision-focused numerologist helping clients align their names with their destiny.",
    image: astro3,
    online: false,
    isPaid: true,
    price: 26,
    color: 'from-lime-600/20 to-green-700/20'
  },
  {
    id: "shivram-mani-pandit",
    name: "Pandit Shivram Mani",
    category: "Career",
    specialization: "Promotion & Career Transitions",
    experience: "11 Years Experience",
    consultations: "6,900+",
    rating: 4.8,
    reviews: 2200,
    languages: ["Tamil", "English", "Sanskrit"],
    bio: "Specialist in timing career moves and ensuring success in professional changes.",
    image: astro1,
    online: true,
    isPaid: true,
    price: 31,
    color: 'from-blue-700/20 to-indigo-800/20'
  },
  {
    id: "megha-bajaj-astro",
    name: "Astro Megha Bajaj",
    category: "Tarot",
    specialization: "Relationship Clarity & Personal Growth",
    experience: "3 Years Experience",
    consultations: "1,500+",
    rating: 4.6,
    reviews: 420,
    languages: ["Hindi", "English"],
    bio: "Modern Tarot reader providing intuitive answers to daily life questions.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 20,
    color: 'from-pink-600/20 to-rose-800/20'
  },
  {
    id: "ramakant-vyas-guru",
    name: "Guruji Ramakant Vyas",
    category: "Vastu",
    specialization: "Industrial Vastu & Factory Layouts",
    experience: "14 Years Experience",
    consultations: "9,800+",
    rating: 4.9,
    reviews: 3500,
    languages: ["Hindi", "Rajasthani", "Gujarati"],
    bio: "Consultant for large industries, focusing on productivity and financial flow through Vastu.",
    image: astro2,
    online: true,
    isPaid: true,
    price: 40,
    color: 'from-red-600/20 to-orange-700/20'
  },
  {
    id: "sangeeta-dhar-acharya",
    name: "Acharya Sangeeta Dhar",
    category: "Health",
    specialization: "Chronic Health Issues & Healing",
    experience: "10 Years Experience",
    consultations: "5,700+",
    rating: 4.7,
    reviews: 1600,
    languages: ["Bengali", "Hindi", "English"],
    bio: "Vedic health consultant providing remedies for long-term health challenges.",
    image: astro3,
    online: true,
    isPaid: true,
    price: 33,
    color: 'from-emerald-700/20 to-teal-800/20'
  },
  {
    id: "gagan-deep-pandit",
    name: "Pandit Gagan Deep",
    category: "Love",
    specialization: "Compatibility & Pre-Marriage Guidance",
    experience: "9 Years Experience",
    consultations: "6,100+",
    rating: 4.8,
    reviews: 1800,
    languages: ["Punjabi", "Hindi", "English"],
    bio: "Expert in Kundli matching and advising on relationship compatibility.",
    image: astro1,
    online: false,
    isPaid: true,
    price: 27,
    color: 'from-purple-700/20 to-violet-800/20'
  }
];

export const getAstrologerBySlug = (slug: string) => {
  return astrologers.find(a => a.id === slug);
};
