/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KundliRouteImport } from './routes/kundli'
import { Route as HoroscopeRouteImport } from './routes/horoscope'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as AstrologersRouteImport } from './routes/astrologers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictionIndexRouteImport } from './routes/prediction.index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator.index'
import { Route as PredictionLoveRouteImport } from './routes/prediction.love'
import { Route as PredictionHealthRouteImport } from './routes/prediction.health'
import { Route as PredictionFutureRouteImport } from './routes/prediction.future'
import { Route as PredictionCareerRouteImport } from './routes/prediction.career'
import { Route as ChatNameRouteImport } from './routes/chat.$name'
import { Route as CelebritySlugRouteImport } from './routes/celebrity.$slug'
import { Route as CalculatorVastuRouteImport } from './routes/calculator.vastu'
import { Route as CalculatorNumerologyRouteImport } from './routes/calculator.numerology'
import { Route as CalculatorMuhuratRouteImport } from './routes/calculator.muhurat'
import { Route as CalculatorLoveRouteImport } from './routes/calculator.love'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KundliRoute = KundliRouteImport.update({
  id: '/kundli',
  path: '/kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRoute = HoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologersRoute = AstrologersRouteImport.update({
  id: '/astrologers',
  path: '/astrologers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionIndexRoute = PredictionIndexRouteImport.update({
  id: '/prediction/',
  path: '/prediction/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionLoveRoute = PredictionLoveRouteImport.update({
  id: '/prediction/love',
  path: '/prediction/love',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionHealthRoute = PredictionHealthRouteImport.update({
  id: '/prediction/health',
  path: '/prediction/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionFutureRoute = PredictionFutureRouteImport.update({
  id: '/prediction/future',
  path: '/prediction/future',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionCareerRoute = PredictionCareerRouteImport.update({
  id: '/prediction/career',
  path: '/prediction/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNameRoute = ChatNameRouteImport.update({
  id: '/chat/$name',
  path: '/chat/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebritySlugRoute = CelebritySlugRouteImport.update({
  id: '/celebrity/$slug',
  path: '/celebrity/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorVastuRoute = CalculatorVastuRouteImport.update({
  id: '/calculator/vastu',
  path: '/calculator/vastu',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorNumerologyRoute = CalculatorNumerologyRouteImport.update({
  id: '/calculator/numerology',
  path: '/calculator/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorMuhuratRoute = CalculatorMuhuratRouteImport.update({
  id: '/calculator/muhurat',
  path: '/calculator/muhurat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorLoveRoute = CalculatorLoveRouteImport.update({
  id: '/calculator/love',
  path: '/calculator/love',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrologers': typeof AstrologersRoute
  '/chatbot': typeof ChatbotRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calculator/love': typeof CalculatorLoveRoute
  '/calculator/muhurat': typeof CalculatorMuhuratRoute
  '/calculator/numerology': typeof CalculatorNumerologyRoute
  '/calculator/vastu': typeof CalculatorVastuRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/chat/$name': typeof ChatNameRoute
  '/prediction/career': typeof PredictionCareerRoute
  '/prediction/future': typeof PredictionFutureRoute
  '/prediction/health': typeof PredictionHealthRoute
  '/prediction/love': typeof PredictionLoveRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/prediction/': typeof PredictionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrologers': typeof AstrologersRoute
  '/chatbot': typeof ChatbotRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calculator/love': typeof CalculatorLoveRoute
  '/calculator/muhurat': typeof CalculatorMuhuratRoute
  '/calculator/numerology': typeof CalculatorNumerologyRoute
  '/calculator/vastu': typeof CalculatorVastuRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/chat/$name': typeof ChatNameRoute
  '/prediction/career': typeof PredictionCareerRoute
  '/prediction/future': typeof PredictionFutureRoute
  '/prediction/health': typeof PredictionHealthRoute
  '/prediction/love': typeof PredictionLoveRoute
  '/calculator': typeof CalculatorIndexRoute
  '/prediction': typeof PredictionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrologers': typeof AstrologersRoute
  '/chatbot': typeof ChatbotRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calculator/love': typeof CalculatorLoveRoute
  '/calculator/muhurat': typeof CalculatorMuhuratRoute
  '/calculator/numerology': typeof CalculatorNumerologyRoute
  '/calculator/vastu': typeof CalculatorVastuRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/chat/$name': typeof ChatNameRoute
  '/prediction/career': typeof PredictionCareerRoute
  '/prediction/future': typeof PredictionFutureRoute
  '/prediction/health': typeof PredictionHealthRoute
  '/prediction/love': typeof PredictionLoveRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/prediction/': typeof PredictionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astrologers'
    | '/chatbot'
    | '/horoscope'
    | '/kundli'
    | '/login'
    | '/signup'
    | '/calculator/love'
    | '/calculator/muhurat'
    | '/calculator/numerology'
    | '/calculator/vastu'
    | '/celebrity/$slug'
    | '/chat/$name'
    | '/prediction/career'
    | '/prediction/future'
    | '/prediction/health'
    | '/prediction/love'
    | '/calculator/'
    | '/prediction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrologers'
    | '/chatbot'
    | '/horoscope'
    | '/kundli'
    | '/login'
    | '/signup'
    | '/calculator/love'
    | '/calculator/muhurat'
    | '/calculator/numerology'
    | '/calculator/vastu'
    | '/celebrity/$slug'
    | '/chat/$name'
    | '/prediction/career'
    | '/prediction/future'
    | '/prediction/health'
    | '/prediction/love'
    | '/calculator'
    | '/prediction'
  id:
    | '__root__'
    | '/'
    | '/astrologers'
    | '/chatbot'
    | '/horoscope'
    | '/kundli'
    | '/login'
    | '/signup'
    | '/calculator/love'
    | '/calculator/muhurat'
    | '/calculator/numerology'
    | '/calculator/vastu'
    | '/celebrity/$slug'
    | '/chat/$name'
    | '/prediction/career'
    | '/prediction/future'
    | '/prediction/health'
    | '/prediction/love'
    | '/calculator/'
    | '/prediction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologersRoute: typeof AstrologersRoute
  ChatbotRoute: typeof ChatbotRoute
  HoroscopeRoute: typeof HoroscopeRoute
  KundliRoute: typeof KundliRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CalculatorLoveRoute: typeof CalculatorLoveRoute
  CalculatorMuhuratRoute: typeof CalculatorMuhuratRoute
  CalculatorNumerologyRoute: typeof CalculatorNumerologyRoute
  CalculatorVastuRoute: typeof CalculatorVastuRoute
  CelebritySlugRoute: typeof CelebritySlugRoute
  ChatNameRoute: typeof ChatNameRoute
  PredictionCareerRoute: typeof PredictionCareerRoute
  PredictionFutureRoute: typeof PredictionFutureRoute
  PredictionHealthRoute: typeof PredictionHealthRoute
  PredictionLoveRoute: typeof PredictionLoveRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  PredictionIndexRoute: typeof PredictionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundli': {
      id: '/kundli'
      path: '/kundli'
      fullPath: '/kundli'
      preLoaderRoute: typeof KundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope': {
      id: '/horoscope'
      path: '/horoscope'
      fullPath: '/horoscope'
      preLoaderRoute: typeof HoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologers': {
      id: '/astrologers'
      path: '/astrologers'
      fullPath: '/astrologers'
      preLoaderRoute: typeof AstrologersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/': {
      id: '/prediction/'
      path: '/prediction'
      fullPath: '/prediction/'
      preLoaderRoute: typeof PredictionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/love': {
      id: '/prediction/love'
      path: '/prediction/love'
      fullPath: '/prediction/love'
      preLoaderRoute: typeof PredictionLoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/health': {
      id: '/prediction/health'
      path: '/prediction/health'
      fullPath: '/prediction/health'
      preLoaderRoute: typeof PredictionHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/future': {
      id: '/prediction/future'
      path: '/prediction/future'
      fullPath: '/prediction/future'
      preLoaderRoute: typeof PredictionFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/career': {
      id: '/prediction/career'
      path: '/prediction/career'
      fullPath: '/prediction/career'
      preLoaderRoute: typeof PredictionCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$name': {
      id: '/chat/$name'
      path: '/chat/$name'
      fullPath: '/chat/$name'
      preLoaderRoute: typeof ChatNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity/$slug': {
      id: '/celebrity/$slug'
      path: '/celebrity/$slug'
      fullPath: '/celebrity/$slug'
      preLoaderRoute: typeof CelebritySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/vastu': {
      id: '/calculator/vastu'
      path: '/calculator/vastu'
      fullPath: '/calculator/vastu'
      preLoaderRoute: typeof CalculatorVastuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/numerology': {
      id: '/calculator/numerology'
      path: '/calculator/numerology'
      fullPath: '/calculator/numerology'
      preLoaderRoute: typeof CalculatorNumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/muhurat': {
      id: '/calculator/muhurat'
      path: '/calculator/muhurat'
      fullPath: '/calculator/muhurat'
      preLoaderRoute: typeof CalculatorMuhuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/love': {
      id: '/calculator/love'
      path: '/calculator/love'
      fullPath: '/calculator/love'
      preLoaderRoute: typeof CalculatorLoveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologersRoute: AstrologersRoute,
  ChatbotRoute: ChatbotRoute,
  HoroscopeRoute: HoroscopeRoute,
  KundliRoute: KundliRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CalculatorLoveRoute: CalculatorLoveRoute,
  CalculatorMuhuratRoute: CalculatorMuhuratRoute,
  CalculatorNumerologyRoute: CalculatorNumerologyRoute,
  CalculatorVastuRoute: CalculatorVastuRoute,
  CelebritySlugRoute: CelebritySlugRoute,
  ChatNameRoute: ChatNameRoute,
  PredictionCareerRoute: PredictionCareerRoute,
  PredictionFutureRoute: PredictionFutureRoute,
  PredictionHealthRoute: PredictionHealthRoute,
  PredictionLoveRoute: PredictionLoveRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  PredictionIndexRoute: PredictionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
